### ISSUE TITLE
Games: Improve Rendering Engine

### ISSUE THREAD

**Issue by ZigaByte** [Jeremy-Barnes/Critters#109]
Rendering is handled by different renderers and scaling only works awkwardly. 
- [x] Create a class that holds all the renderers and rendering methods.
- [x]  Replace existing SpriteBatch and the static ShapeRenderer with new class methods
- [x]  Implement a camera to get rid of scaling issues.

Or as Jeremy would say: "Do that camera thing, like tower defense!"

**Comment by ZigaByte** [comment]
More games that need it. 

- [ ] Breakout
- [ ] SpaceInvaders
- [ ] Snake - half done already.

**Comment by Jeremy-Barnes** [comment]
Cancelling since Phaser games are simpler and faster. LibGDX is dead!
