### ISSUE TITLE
Games: Implement Timing Engine

### ISSUE THREAD

**Issue by ZigaByte** [Jeremy-Barnes/Critters#112]
All games work on a non-constant deltaTime depending on the FPS. This should generally not be an issue, but making it really properly and not relying on the Gdx built in FPS stabilizer should improve the game.

Implement for the following games:
- [x] Snake
- [x] Breakout
- [x] Space Invaders
- [ ] Whacamole

**Comment by ZigaByte** [comment]
Look at PolygonDefense for further info.
[https://github.com/ZigaByte/PolygonDefense/commit/177197745861f36c03ecb47a77cbde72c7491a87](Commit Link)

**Comment by Jeremy-Barnes** [comment]
Boom get this done by Monday, and then start on Flapping Bird!

**Comment by ZigaByte** [comment]
All done except Whacamole. That's not even a thing yet.

**Comment by Jeremy-Barnes** [comment]
Cool. I think we can close this, and when you do whackamole, just do it with the timing engine the first time
