### ISSUE TITLE
Mobile Interface

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#115]
Figure out the UI for the sidebar and navbar on mobile.

**Comment by jillkgraves** [comment]
@ZigaByte @Sparrowmittens @Jeremy-Barnes 

This is pretty straightforward, but do you guys have any comments?

![create account mobile](https://cloud.githubusercontent.com/assets/21324742/21088393/3915010a-bff4-11e6-95f9-8f064364805b.png)
![create account mobile search](https://cloud.githubusercontent.com/assets/21324742/21088394/3b38facc-bff4-11e6-82b8-02986234276b.png)
![create account mobile sidebar](https://cloud.githubusercontent.com/assets/21324742/21088395/3d47168c-bff4-11e6-97c5-84b6f533f165.png)

**Comment by Jeremy-Barnes** [comment]
I actually do have a thing - should we have a button to dismiss the mobile sidebar, or do you want to just to the "click on the background" approach?

**Comment by jillkgraves** [comment]
I like "click on background"
