### ISSUE TITLE
Polygon Defense UI Design

### ISSUE THREAD

**Issue by ZigaByte** [Jeremy-Barnes/Critters#131]
Create a UI Design for a tower defense game called Polygon Defense. The game revolves around regular polygons and geometry and so should the UI.

[A game demo is available in Demos folder of our Google Drive.](https://drive.google.com/open?id=0B7xNmGFtCTqbdHZvdmt6OFhURU0) Here is also a screenshot of the game.

![Screenshot](http://i.imgur.com/aRyYAp6.png)

There are several elements that need designing:

- Bottom dock that includes a Life Counter (preferably in progress bar form), Money Display (just a number and $) and a message area (as in - "Wave 12" or "Not enough money" or "Blocked").

- Build buttons. The game includes 5 buttons for placing different towers in the top dock. Each button should have enough space for a price tag and a polygon for indicating the type? Also a sell button? Not sure where

- A pause button in one of the corners that brings up the pause menu, which does not have to be designed, but the pause button itself would be nice to have.

- Upon clicking a tower or a mob there should be some sort of popup. I need input on that. Player should be able to see basic stats of mob/tower (damage, speed, health, range..). And in case of the tower have an upgrade and a sell button on that popup (or some menu that switches?). If anyone has any ideas, it's open to suggestions.

I would be very thankful if this got designed as I am terrible at it myself (as shown by the screenshot :) ). Any changes/imporvements/suggestions on the things above are welcome. If everything can somehow be put into the bottom dock with it switching around or something, that would be perfect :).

**Comment by jillkgraves** [comment]
Default view:
Build dock at the top
Status bar at the bottom

![ui-mockup-default](https://cloud.githubusercontent.com/assets/21324742/20953640/b67b09b2-bbfa-11e6-9d7f-ff58afe969c2.png)

Build info popup view:
Also shows what degraded health looks like

![ui-mockup-popup-1](https://cloud.githubusercontent.com/assets/21324742/20953642/b68c3b56-bbfa-11e6-8019-ed3886c07861.png)

Tower info popup view:

![ui-mockup-popup-2](https://cloud.githubusercontent.com/assets/21324742/20953641/b6888b5a-bbfa-11e6-9349-222b3216cf90.png)

General: I think adding a circle around each tower to show its range would be good.
I think the mobs should go green - yellow - red as their health degrades, not green - brown - red.

I could do some hover/rollover states for the build buttons if you would like as well.

**Comment by jillkgraves** [comment]
Also: on the popups, I think this would be fine as long as there are gaps in between enemy waves where the user has as long as needed to review and build their setup before the next round. But if the user doesn't have control of that, I think having the popups over the map might be bad, and we could move it into a sidebar instead.

**Comment by ZigaByte** [comment]
It looks great!

I am not yet what the wave speed is going to be, but the current setup is temporary.

Do you think the range indicators should be visible at all times or just when the pop-up is active?

Could you also please upload or link to this Photoshop file so I can easily extract individual images? Thank you

**Comment by jillkgraves** [comment]
[Here is the PSD file.](https://drive.google.com/file/d/0Bz0aNMRvWjT_dEIyZ2QwY2NrUEk/view?usp=sharing)

I think the range indicators should at least be visible when placing a new tower and when the popup is active. They could probably be hidden other times.

**Comment by Jeremy-Barnes** [comment]
Can we close this issue???

**Comment by ZigaByte** [comment]
Yes.
