### ISSUE TITLE
Space Invaders - Doesn't load on mobile

### ISSUE THREAD

**Issue by jillkgraves** [Jeremy-Barnes/Critters#141]
![screenshot_20170116-203849](https://cloud.githubusercontent.com/assets/21324742/22005844/20d960dc-dc2c-11e6-866b-331f86f8605a.png)

**Comment by Jeremy-Barnes** [comment]
@jillkgraves can you reproduce this consistently? I cannot get this to happen on my device.

**Comment by jillkgraves** [comment]
Yeah, I'm still getting this error. Do I just not have Arial on my phone?

**Comment by Jeremy-Barnes** [comment]
Seems like it, but we still need to solve this because if your phone came fucked up like that, other people's phones probably did too.

**Comment by jillkgraves** [comment]
This is loading for me, now.
