### ISSUE TITLE
Breakout - Slow-down powerup

### ISSUE THREAD

**Issue by jillkgraves** [Jeremy-Barnes/Critters#144]
The light blue powerup (slow-down) doesn't take effect until the next time the ball hits the paddle. This seems weird to me. I think it should take effect instantly.

**Comment by ZigaByte** [comment]
Could it be possible you are running an older version on the server. This has already been fixed in my local version.

**Comment by Jeremy-Barnes** [comment]
Interesting, I'll double check the build server and make sure its pulling from your branch and not master. Is the code on your branch up to date?

**Comment by ZigaByte** [comment]
I just pushed my branch. Please merge, build and test.

**Comment by Jeremy-Barnes** [comment]
Branch config was correct.
Games take a billion years to compile, so the game branch compiles alone, just check in anything with the word "build" in it on the games branch and the server will pick it up.

**Comment by jillkgraves** [comment]
This works as expected now. On a side note, @ZigaByte did you change the chance of getting a blue powerup just for testing purposes? Every block gave me a blue powerup, picking them all up was a mistaaaaake.

**Comment by ZigaByte** [comment]
Hah. I am a dummy. I did, will be fixed in the next patch.

**Comment by Jeremy-Barnes** [comment]
10/10 good work team
