### ISSUE TITLE
Breakout - Dark red powerup?

### ISSUE THREAD

**Issue by jillkgraves** [Jeremy-Barnes/Critters#145]
Does this actually do anything? I couldn't figure it out. It didn't seem to change the score, speed, or paddle size.

**Comment by Jeremy-Barnes** [comment]
@ZigaByte this is part of Bughunt #118 , can you answer this?

**Comment by ZigaByte** [comment]
From the top of my head. It should be the FireBallPowerup, which causes the ball to plough through all the destructible objects.

The brown increases the size and the blue slows the ball down.

**Comment by Jeremy-Barnes** [comment]
@jillkgraves with that in mind can you revisit whatever this was about and see if it is in fact a bug?

**Comment by jillkgraves** [comment]
@ZigaByte Okay, in that case it seems to be working as intended.
