### ISSUE TITLE
Game: Snake

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#15]
Implement game [Snake](https://en.wikipedia.org/wiki/Snake_(video_game))

- [x] Snake tail should grow with each objective eaten.

- [x] Objectives should spawn randomly on the map one at a time and remain until eaten.

- [x] Obstacles which cannot be eaten and do not go away should spawn randomly (but infrequently).

- [x] Game should have 3 difficulty modes (Easy/Medium/Hard) which increase player speed and the frequency with which Obstacles spawn. Modes also modify point values of each objective - Easy = 1x, Medium = 2x, Hard = 4x;

- [x]  There should be 5 types of objective (normal, double point, triple point, quadruple point, special) which can spawn, randomly chosen, weighted 75% normal, 15% double, 8% triple, 1% quadruple, 1% special

- [x] Special objective should double player speed for 5 seconds once eaten and triple the score of all objectives eaten til effect wears off.

**Comment by ZigaByte** [comment]
Nah, I just made the basic game. Good for now. Will revisit the modes thing later.

**Comment by Jeremy-Barnes** [comment]
Nah?

**Comment by ZigaByte** [comment]
I checked what I have made in my last commits. Other stuff will wait :P

**Comment by Jeremy-Barnes** [comment]
:P thats fine, but that means the issue is still open

**Comment by Jeremy-Barnes** [comment]
@ZigaByte You're in trouble!

**Comment by ZigaByte** [comment]
I told you I was going to leave this for the next date! That's why I closed it. I deemed it finished.

**Comment by Jeremy-Barnes** [comment]
The next date is wednesday, reopened for the remaining issues and moved to prealpha. Due in 3 days!

**Comment by ZigaByte** [comment]
Added all the things.

Difficulty is chosen with numbers 1, 2 and 3 on the keyboard.
