### ISSUE TITLE
Breakout: Levels don't advance

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#161]
This may not actually be a bug, but I thought you had programmed some other levels into breakout:

When you clear a stage in breakout, the same stage comes back as the next level, instead of a new one. This happens up to at least level 4 (when I gave up).

**Comment by ZigaByte** [comment]
Oh yeah. The leveling is implemented, but there only is one level at the moment.

**Comment by Jeremy-Barnes** [comment]
Okay cool, then this isn't a bug and I'll close it out.
