### ISSUE TITLE
Breakout: Floor shouldn't bounce

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#17]
When the ball misses the player's paddle in Breakout, hitting the floor, it should leave the screen as if falling below the window and trigger a failure state, displaying the player's final score.

Currently, the floor is merely a surface that the ball can bounce off of.

**Comment by ZigaByte** [comment]
This was a debug feature and it will be removed in the 'Removed Floor' commit.
