### ISSUE TITLE
Breakout: Levels

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#18]
- [x] When a level is cleared, the game should reset to a non-moving ball, centered paddle, and regenerating bricks. 

- [x] Create format for specifying levels as resources to be packaged with the game. Specification should be able to set level shape and specific blocks (void, X-Hit, obstacle, normal). We will later make a tool for writing this format.

- [x] Each level should randomly choose its shape based on a predefined list of patterns (see [here](http://www.gamasutra.com/view/feature/1630/breaking_down_breakout_system_and_.php?print=1) for patterns to implement

**Comment by ZigaByte** [comment]
Please clarify regenerating bricks? As in animation when they come into view, or do they all pop up, or 1 by one?

**Comment by Jeremy-Barnes** [comment]
Sorry, I worded that super poorly. When a level is cleared, the next level should load (which will generate/create a new set of blocks in a different pattern).

I do not mean that in one level a block will come back.

@ZigaByte (flagged so it shows up in your notifications).

**Comment by Jeremy-Barnes** [comment]
No need to do any sort of animation where the next level pops in one brick at a time.

**Comment by ZigaByte** [comment]
Implemented 4 level patterns that are chosen at random. (wall, mesh, columns and central mass)

**Comment by ZigaByte** [comment]
Level now detects its state and the game creates a new level if this one has been won or lost.

**Comment by ZigaByte** [comment]
Random does now randomly spawn. I am unsure how to integrate difficulty.

**Comment by Jeremy-Barnes** [comment]
Mmm so I was initially thinking it would be like, each block would be generated something like this:

`for(int x = 0; x < rows; x++){
    for(int y = 0; y < cols; y++){
          double randFactor = random.double * level;
          blocks[x][y] = randFactor < .5 ? normal block : randFactor == .6 ? solidBlock : randFactor >.6 ? multiblock; 
`
But I think it would be better if we just had static, designed levels. It occurred to me that random generation could make an unplayable level. I've edited the issue with a better plan.

**Comment by Jeremy-Barnes** [comment]
My recommendation for creating the level format:

Each level will be in a file with the level number on it (1.lev), and then read in at runtime.
Levels should be specified as a comma separated list of strings

If we have a pretty easy format, we can have non-programmers write levels without a level editor.

A simple format might be to specify a cell as `{properties}`
So a cell with no block might be `{}`
A 1-hit block might be `{1}`
A 3-hit '{3}'
An obstacle: '{O}`
A voidblock: '{V}`

And then a level would be specified as a grid of cells
`{}{1}{1}{1}{1}{}
{}{1}{V}{1}{1}{}
{}{O}{O}{O}{}`

**Comment by ZigaByte** [comment]
Added the loader.
