### ISSUE TITLE
Breakout: Brick Types

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#19]
- [ ] Bricks should track the number of times they have been hit as well as the number of hits required to destroy them. They should not be destroyed until these numbers match.

- [ ] Special Brick: Some bricks cannot be destroyed, acting simply as obstacles, but their presence should not prevent the level from advancing when all normal bricks are destroyed.

- [ ] Special Brick: Rarely, a brick should spawn that takes one hit to destroy and, when destroyed, does not change the direction of the ball

- [ ] Normal brick types: 1 hit, 2 hit, 4 hit (to destroy).

**Comment by ZigaByte** [comment]
Brick types implemented in 3 commits:

- Added BlockVoid  …
- Added BlockIndestructible  …
- Added BlocksMulti  …

**Comment by Jeremy-Barnes** [comment]
What is blockvoid?

**Comment by ZigaByte** [comment]
BlockVoid is a special type of brick that allows balls to pass through as described above.

**Comment by Jeremy-Barnes** [comment]
Got it. I was afraid you were marking empty space with a special kind of block (like minecraft air).
