### ISSUE TITLE
Breakout: Powerups

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#20]
Create a framework for powerups. Extension (adding new powerups in the future) should be trivial with this system.

- [x] Each brick has a random (lowish) chance of holding a powerup

- [x] Upon level generation, each brick "decides" if it has a powerup, and what powerup it has.

- [x] When a brick is destroyed, its powerup falls from the position that the brick was in

- [x] Powerups are applied to the player if they hit the player's paddle.

- [x] Powerups are temporary and last for a time specific to that power up.

- [x] Powerups can stack (Example: if the player gets 2 Big Paddle Powerups, their paddle should increase to 400%  -> ((size * 2 ) * 2)

- [x] Stacked Powerups wear off independently based on their own timers, not simultaneously.

Powerups to create in the beginning:

- [x] Slow ball:
    - Duration: 15 seconds
    - Effect: Ball's velocity is reduced by 50%

- [x] Big Paddle:
    - Duration: 45 seconds
    - Effect: Player's paddle size is increased by 100%

- [x] Fire ball:
    - Duration: 10 seconds
    - Effect: ball immediately destroys all boxes it comes in contact with (except obstacle boxes) and does not change direction

**Comment by ZigaByte** [comment]
Are powerups kept in level(s) x+y (when y > 0) if acquired in level x.

**Comment by Jeremy-Barnes** [comment]
Not positive that I am interpreting this question right, but I'll answer what I think you're asking:

If you acquire the "fire ball" powerup in level 3 and your ball destroys the last block with 7 seconds left on the fireball clock, the fireball should persist for the remaining 7 seconds in the next level, level 4.

**Comment by ZigaByte** [comment]
Yes. That was exactly my question. Thank you.

Also. Oh no! How do I implement this elegantly!?

**Comment by Jeremy-Barnes** [comment]
Hahaha cool. Glad my edit helped. You might have a boolean "isForever" to govern the ones that don't get reset at level change.

The reason for the "forever" changes is we will later have power-downs, like "smaller paddle" that last forever until you get a "big paddle" power up (which, upon expiry, would return you to a normal paddle). That makes gameplay a liiiiittle more strategic.

**Comment by ZigaByte** [comment]
Let the permanent effects be a problem for the future haha.

**Comment by ZigaByte** [comment]
All should be implemented.
