### ISSUE TITLE
Game: Space Invaders

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#21]
Implement game [Space Invaders.](https://en.wikipedia.org/wiki/Space_Invaders)

- [x]  4 defenses each in an upside down U shape

- [x] Defenses are damaged when struck with bullets from enemies _or player_

- [x] Defenses should "wear down" as they take damage, shrinking at the point of projectile impact, creating gaps when struck enough in the same place.

- [x] Player should have 5 lives, resetting on the far right side of the screen when destroyed, or ending the game if lives == 0

- [x] Implement [powerup system like Breakout](https://github.com/Jeremy-Barnes/Critters/issues/20), enemies drop powerups (if they have them) when destroyed
    - [x] Starting powerups to create: +1 Life (no expiry, just `lives++`), Laser Gun (2 shots, creates solid vertical line that destroys all enemies in path, after second shot, expires)

- [x] Levels should advance when all enemies are destroyed, keeping the barrier damage state in place, but creating new enemies

- [x] Allow for different types of enemies worth different amounts of points and requiring different numbers of hits to kill with different representations.

**Comment by ZigaByte** [comment]
That degrading defense things sounds hard.

**Comment by Jeremy-Barnes** [comment]
I imagine it is. Space invaders is a solved problem, though, I bet you can find a million Java implementations on how to do the defenses.

**Comment by Jeremy-Barnes** [comment]
Maaaaaaybe easiest to just treat each shield as a collection of like 30 blocks, each block is destroyed on impact?
http://imgur.com/a/xxW5P

Then its basically the same logic as breakout.

4 shields, 30 blocks each, 120 objects shouldn't be terrible to manage in JS, performance wise.

If we're super worried about performance, a boolean array is easy enough for collision detection and rendering.

```
If(shield[x][y] == true) {
 bullet collides and stops
}
```


```
If(shield[x][y] == true) {
 render block
}
```

```
If(shield[x][y] == false) {
 continue, bullet keeps moving.
}
```

**Comment by ZigaByte** [comment]
That's seems simple enough. I might try the array first

**Comment by ZigaByte** [comment]
With the last batch of commits I deem this issue CLOSED.
