### ISSUE TITLE
Game: Flapping Bird

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#22]
Create side scroller game where user must keep flying character afloat without hitting ceiling, floor, or obstacles.

Ceiling/floor should be able to be shaped (not just a straight line), this will allow us to create distinct levels

Distance/time in the air => points.

Floating objectives that can be picked up for extra points
Floating [powerups ](https://github.com/Jeremy-Barnes/Critters/issues/20)(Start with: Shield - 30 seconds OR one collision, effect: player does not die from obstacle strike)

**Comment by ZigaByte** [comment]
How do I deal with obstructions mid air and the shield powerup? Should the bird just skip through it?

**Comment by Jeremy-Barnes** [comment]
Yeah, destroy it and keep moving. Like the fire ball in Breakout

**Comment by ZigaByte** [comment]
This is more or less complete. Still improvements needed on entity spawning and getting rid of old ones that get off the screen.
