### ISSUE TITLE
Breakout: Teleporting

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#24]
On mobile, tapping the screen immediately moves the paddle (teleports) to the tap location, making the game impossible to lose for anyone semi-competent. 

In all cases, the paddle should have a consistent, moderate speed. Users should be able to move the paddle left or right at the same speed by pressing A or D, Left/Right Arrow, moving the mouse to the left or right of the bat, or pressing the screen left or right of the bat. 

For mobile: a screen tap should move the paddle in the direction of the tap until pressure is released, at which point the paddle stops. This will allow the user to effectively treat the outer edges of the screen as buttons for moving the paddle. 

To allow keyboard play, if a direction key (A/D/arrows) is pressed, mouse position should be ignored until the mouse moves again (switching 'modes'). If the mouse moves, reactivating mouse position tracking, and then a direction key is pressed again, mouse tracking should be deactivated again. Users can switch modes as much as they like.

**Comment by ZigaByte** [comment]
Added Keyboard input. 

There are now 3 modes for input. First is following the pointer, second is going left or right depending on the press location on the screen. Third is keyboard.

Might need to remove one of the mouse modes, more testing needed on mobile to confirm. Input might seem funny.

**Comment by Jeremy-Barnes** [comment]
Nice. If you merge this up to master you can test on mobile.

**Comment by Jeremy-Barnes** [comment]
Pretty good, but not quite there yet. Issues:

- Paddle sticks to the sides on mobile. If you push it all the way to the right edge and then try to move it left, it will stick for ~1.5 seconds of holding, and it simply doesn't respond to rapid taps to try to nudge it a little to the left.

- Mouse/keyboard conflict on PC : if you click the screen, the paddle doesn't follow the mouse pointer, which is bad. Clicking is natural when pointing and shouldn't disable the pointer-follow. Worse, clicking disables pointer follow and pressing an arrow key moves the paddle as expected, but then turns on pointer follow, which is very confusing.

**Comment by Jeremy-Barnes** [comment]
Looks like everyone is happy with the way this controls. Good work, closing the issue.
