### ISSUE TITLE
Trade: Shops

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#33]
Design the shop layout for an NPCs shop.

Shops should have a discrete location (continent/world) and therefore have a general theme based upon location. NPC shops may also have themes specific to their shop owner that overrides or coexists with location theming. Shops should display the title of the shop.

Shop owners should be a visible character who appears above or alongside their items. The page should have a location to display a quote from the shop owner and the owner's name/title, controls (buttons, dropdowns) if the shop owner is also a quest NPC.

Shops should show all available items along with their name and price. Flavor text should be visible on hover or click (mobile can't hover).

**Comment by jillkgraves** [comment]
@Jeremy-Barnes @ZigaByte @Sparrowmittens 
User will be able to use the search function to find a particular item in the shop, or sort by Name A-Z or Price High-to-Low/Low-to-High.

On click, modal will appear, displaying more information. The Buy button has sections to increase or decrease quantity. The price indicator should increase as quantity goes up.

![shop](https://cloud.githubusercontent.com/assets/21324742/19623261/97b309fc-9888-11e6-9c2c-773b228385bb.png)

![shop modal](https://cloud.githubusercontent.com/assets/21324742/19623262/99c9dcf2-9888-11e6-82e0-be28f9875c56.png)

**Comment by Jeremy-Barnes** [comment]
Big red cancel button!

**Comment by jillkgraves** [comment]
I feel that is unnecessary, I'm curious what Ziga and Grace think.

The modal should dismiss by clicking the x in the corner or by clicking on any of the area outside of it. That seems sufficient to me.

**Comment by Jeremy-Barnes** [comment]
@ZigaByte @Sparrowmittens thoughts on this overall and on the need/lack of need for a parallel big red cancel button?

@jillkgraves due in 3 days.

**Comment by ZigaByte** [comment]
I like the overall design. 

The big red button might be good to add as a third option of canceling the pop up ( I am assuming clicking beside it will close it also).

**Comment by Jeremy-Barnes** [comment]
Adding this for the record - Jill and I discussed this a little yesterday and she pointed out that a red cancel button dilutes the importance of red, making people less likely to pay attention to it when it really is a big deal (<red>"ARE YOU SURE YOU WANT TO DELETE THIS ITEM?"</red>). 

I think thats a super good point, so we might try a gray or other colored cancel button.

**Comment by Sparrowmittens** [comment]
Yeah, I'll throw in that it could use a cancel button, making it a light gray wouldn't be a bad idea, maybe blue or yellow or something?

**Comment by jillkgraves** [comment]
Here's your [normal size] [grey] cancel button. I do not think it needs to have the same weight as the other button since it is not the important piece there. Also since the Buy button text is left aligned, I think it would look weird to have the text centered in the button below it, but it would also look weird to have a big button with the text on the left if there's nothing on the right (like the plus and minus in the buy button).

![shop modal](https://cloud.githubusercontent.com/assets/21324742/19839532/a8fa890e-9eb1-11e6-84ed-f4e536f2b850.png)
