### ISSUE TITLE
Account: Account Creation

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#37]
Create the screen(s) whereby users create their accounts. They _must_ provide, ultimately, 

- Username

- Email address

- Password

- Birthdate

- First name

They can, optionally, provide:

- Last name

- City

- State

- Country

- Postcode

Users cannot create an account without selecting *one* pet - they must choose species, color, and sex (M/F/Other), as well as name.

User names and pet names are site-wide uniques, and so a "check availability" option should exist.

Email addresses must also be unique, but no "check" option exists, because users shouldn't be entering nonsense emails. If creation fails for that reason, form data is retained, but users are notified that the email address is taken.

Users will have 48 hours to "activate" their account once by email once it is created, and they should be notified of such.

**Comment by jillkgraves** [comment]
Comps here: https://drive.google.com/drive/folders/0Bz0aNMRvWjT_Z3JoaWVUX05zaGM?usp=sharing

**Comment by Jeremy-Barnes** [comment]
Need spot to add email in Create Account 1

**Comment by jillkgraves** [comment]
Fuck.

**Comment by jillkgraves** [comment]
@Sparrowmittens @ZigaByte @Jeremy-Barnes 

Any more feedback before I can call this closed?

![1 create account](https://cloud.githubusercontent.com/assets/21324742/18695925/cb5819e0-7f7a-11e6-8407-aae7820e0082.png)
![2 create account p2](https://cloud.githubusercontent.com/assets/21324742/18695926/cb64f2be-7f7a-11e6-9245-141b6c13fcb1.png)
![3 create account p3](https://cloud.githubusercontent.com/assets/21324742/18695929/cb67efb4-7f7a-11e6-812a-34e96aadc4d5.png)
![4 create account p3 hover](https://cloud.githubusercontent.com/assets/21324742/18695927/cb675a72-7f7a-11e6-9316-035b66c0cb11.png)
![5 create account p3 modal](https://cloud.githubusercontent.com/assets/21324742/18695928/cb6809a4-7f7a-11e6-8afb-d839c8dd00f8.png)

**Comment by ZigaByte** [comment]
I think it looks great. A picky improvement in the first screen would be drop down date selection, that way I think there would be less trouble with getting the right format.

**Comment by Jeremy-Barnes** [comment]
@ZigaByte do you mean like a DatePicker? https://www.devexpress.com/Products/NET/Controls/Silverlight/Editors/i/features/date-picker.png

Or is there something else?

**Comment by ZigaByte** [comment]
Sort of. Though the system currently implemented that limits your inputs via keyboard is good as well

**Comment by jillkgraves** [comment]
My concern is that it's often difficult to use a date picker for something
far in the past, like a birthday. I think it'll be good to use for picking
an date in the future, though.

**Comment by Jeremy-Barnes** [comment]
@Sparrowmittens  Graaaaaaaaace

**Comment by Sparrowmittens** [comment]
Everything looks good to me, it feels like it's easier to manually enter a
birthday in a specific format than to use drop downs, but that's because I
hate long drop downs.
