### ISSUE TITLE
Account: Update information

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#38]
Users should have a form to change all their account details (email, name, password, etc) except for their Pet information and their Username. Those are _set in stone_

**Comment by Jeremy-Barnes** [comment]
@jillkgraves due in 2 days

**Comment by jillkgraves** [comment]
![edit account info](https://cloud.githubusercontent.com/assets/21324742/19421846/04d3d5a6-93d0-11e6-9695-3f35b2525b22.png)
