### ISSUE TITLE
Account: Add a pet

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#39]
Users should be able to create a new pet at any time, the same way they do in #37.

There may be limits on how many pets a user can have (this may be expandable based on time active or in-game item acquired), but if a user is at their limit, they should be notified and disallowed from proceeding.

**Comment by jillkgraves** [comment]
![create pet](https://cloud.githubusercontent.com/assets/21324742/19060640/71c5732a-89af-11e6-919a-690e25d27fad.png)
![create pet hover](https://cloud.githubusercontent.com/assets/21324742/19060638/71c1e624-89af-11e6-83db-dadb19043001.png)
![create pet modal](https://cloud.githubusercontent.com/assets/21324742/19060639/71c34ab4-89af-11e6-94ca-64931d496fef.png)

**Comment by Jeremy-Barnes** [comment]
Could you add a screen for when you have too many pets and can't add another? It's in the issue.

**Comment by Jeremy-Barnes** [comment]
@jillkgraves due in 2 days

**Comment by jillkgraves** [comment]
![create pet error](https://cloud.githubusercontent.com/assets/21324742/19422029/6656c178-93d3-11e6-8977-aa9422383960.png)
