### ISSUE TITLE
Inventory Screen

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#40]
Users should be able to view all the items in their possession, sorting them by name.

Items should display their item thumbnail and name. 
Click/hover should display flavor text.
Selecting an item should bring up a dialog or context menu that allows them to take context sensitive actions (feed food to pet, equip weapon to pet), as well as options that permanently remove an item from the users inventory with no recompense (WARN), or place an item in the shop.
Users may have a bank vault where they can also store items. They should be able to move items freely between these screens by context menu.

Users should be able to mass-edit items by selecting multiple items and then bringing up a batch context menu with general options (throw away, move to vault, move back to inventory).

**Comment by Jeremy-Barnes** [comment]
@jillkgraves due in 3 days!

**Comment by jillkgraves** [comment]
@ZigaByte @Sparrowmittens @Jeremy-Barnes 

If user selects the bulk select button, the UI changes to have check marks on the corner of each item. Once they've selected all they want, they can use the move or delete buttons that slide in next to the bulk select button. The move button will be a drop down with options such as "sell in shop, sell at auction, send to friend, donate" etc. The delete button will pop up with a warning modal.

If a user just clicks on an item, the right sidebar slides in with more information. This is basically a modal that is anchored to the side - it can be dismissed by clicking the x or clicking outside the sidebar area.

I wanted something a little different from the standard centered modal, but I'm not sure if this is too different. **If we go the sidebar route, should we change the shop interface to match?**

![inventory](https://cloud.githubusercontent.com/assets/21324742/19712081/65369a6e-9b00-11e6-814f-2c1a7dcbbdce.png)
![inventory bulk](https://cloud.githubusercontent.com/assets/21324742/19712084/653ad192-9b00-11e6-8296-5aff0df2ef29.png)
![inventory delete](https://cloud.githubusercontent.com/assets/21324742/19712082/65386970-9b00-11e6-98f6-096a085a71b9.png)
![inventory detail](https://cloud.githubusercontent.com/assets/21324742/19712083/6539070e-9b00-11e6-8b40-c19317cdedc3.png)

**Comment by Jeremy-Barnes** [comment]
I do think the shop interface would benefit from following the same pattern as inventory. I don't have a strong impression on which one should prevail, so long as they match.

**Comment by Jeremy-Barnes** [comment]
Question - the item panel fades everything else darker, the Wait! dialog fades everything whiter. Is that intentional? I don't really care, but it seems odd.

**Comment by Sparrowmittens** [comment]
I feel like If we use the sidebar it should be the same in the shop, but I'm the same as Jeremy in that the shop might not benefit from having a sidebar.

**Comment by jillkgraves** [comment]
Okay, thanks for the sanity check on having it the same as the shop.

![inventory detail](https://cloud.githubusercontent.com/assets/21324742/19839573/6aafd2f2-9eb2-11e6-8449-15d15fc1a1a9.png)

**Comment by Jeremy-Barnes** [comment]
Hmmm I hate that cancel button. No button it is then.
