### ISSUE TITLE
Games: Gameroom

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#44]
Create a screen that allows users to browse all games available on the site. Games will have a title and a thumbnail image. The thumbnail may be a screenshot of the game or more traditional cover-art.

The game room is not necessarily in any world.

The game room may have a "game of the day" worth 2x critterbuxx or similar community events.

**Comment by jillkgraves** [comment]
@Sparrowmittens @ZigaByte @Jeremy-Barnes Any feedback on this? The icons next to each game title would be world/categories signifiers like in the [Game About Page](45)

![game room](https://cloud.githubusercontent.com/assets/21324742/19422607/939642b8-93dc-11e6-8e73-b5aeb3d8a158.png)

**Comment by ZigaByte** [comment]
I like it! Maybe move the find a game in the top bar, next to the game room?

**Comment by Sparrowmittens** [comment]
Looks good!

**Comment by Jeremy-Barnes** [comment]
Hmmm Ziga might be right on this, moving the search bar up. Not sure, theres never a good place for those.

**Comment by jillkgraves** [comment]
Yeah I think that's a good call. Nav features like titles/breadcrumbs/search should go in that top bar. We will probably add a separate sitewide search in the top blue bar or the bottom of the sidebar.

![game room](https://cloud.githubusercontent.com/assets/21324742/19622498/d48582e6-9870-11e6-8dc1-a28f25d3a41d.png)
