### ISSUE TITLE
Games: Game container

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#45]
Design a screen for holding a game -

It should display a users high score and the overall high scores, as well as specific-game theming. Games can be associated with worlds, and some of that theming should be visible.

Instructions for the game may be displayed as a part of the page, not as part of the game itself.

**Comment by jillkgraves** [comment]
@Jeremy-Barnes @ZigaByte @Sparrowmittens 
Okay so the idea here is that game art/theming is visible in that top banner. The icons underneath the title would indicate game type (puzzle, luck, arcade, whatever) and world location.

About the Game would have a brief description and instructions, as well as screenshots.

Suggested Games would show similar options based on game type/world.

Are the games going to display in full screen or do I need to design some sort of window for them to pop out into? Or I think it would be neat if the banner area could expand to become the game container. Idk if that's feasible.

![game container](https://cloud.githubusercontent.com/assets/21324742/19257240/9c43eec2-8f33-11e6-9b44-8f1a1b09e585.png)

**Comment by Jeremy-Barnes** [comment]
They may be playable fullscreen, but we do need a non-fullscreen container.
I'd rather not have the pane expand, because that will introduce scrolling issues.

This looks good though!

**Comment by jillkgraves** [comment]
Would a modal type popup be acceptable? Or does it need to be an actual new window?

**Comment by Jeremy-Barnes** [comment]
Mmmm. Modal might work, its certainly easily codable, but my concern is that typically a modal is dismissed if you click outside of it, which would be infuriating in a game. Tap the wrong area, game over.

**Comment by ZigaByte** [comment]
I imagined the game itself being on a whole different page. Say this design is ../games/breakout/about and the game itself is on ../games/breakout.

I bowe

**Comment by Jeremy-Barnes** [comment]
I bowe?

I had the same impression as Ziga. @jillkgraves, you seem opposed to a separate page, whats your concern?

**Comment by ZigaByte** [comment]
I missclicked multiple times in a row. My bad.

Yes. That would make it easier to have direct links to the game wherever and a separate link for say highscores.

**Comment by jillkgraves** [comment]
Hmm that is fine, it just seemed weird to me because I'm still thinking in terms of a website that was built in 1996. 📃 

Would it still have the usual sidebar on that page or no?

**Comment by Jeremy-Barnes** [comment]
I don't know what that icon after "1996" is.

I don't know, we'd need some controls to navigate away from the game when you're done playing, but I could see no-sidebar being nice. I'm honestly not sure. 

Incidentally, with angular pages aren't really new pages, they don't necessarily involve HTTP calls, so you can switch back and forth between views without losing data.

**Comment by jillkgraves** [comment]
About page
![game about page](https://cloud.githubusercontent.com/assets/21324742/19422644/3ba7edda-93dd-11e6-955f-6eab7e66415d.png)

Simple game container page. Shouldn't be able to scroll. Breadcrumbs in top bar allow user to go back to game detail page or game room.
![game page](https://cloud.githubusercontent.com/assets/21324742/19422648/42a07c38-93dd-11e6-93d4-2fa2282198ad.png)

**Comment by Jeremy-Barnes** [comment]
I'm slightly concerned about the breadcrumb placement, maybe its just because I'm looking at a tiny version of the image instead of fullscreen, but it seems easy to miss.

**Comment by jillkgraves** [comment]
We're going to leave as-is for now and see how it looks in the wild.
