### ISSUE TITLE
General Site: Random Events

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#46]
In the course of navigating the site, a random event may happen, consisting of links, images, and text. These will never be over 300 words, and should not significantly alter the appearance of the page.

They may take the form of popups or injected banners, etc.

("The leaning tower of pizza strolls by and gives you 300 critterbuxx!" {image of the tower waving})

**Comment by Sparrowmittens** [comment]
Here's some progress, photoshop keeps crashing on me so i've lost a few things by just not saving on time, but i have these four things done to some degree.
![site-design2 1](https://cloud.githubusercontent.com/assets/21325925/20084837/9a7c2480-a52a-11e6-8cf1-cad35880b6c5.jpg)

**Comment by jillkgraves** [comment]
Random event should come up from bottom of browser and persist until dismissed by cancel button/close button. Should be about 75% width of page, 85% on mobile.

The random event container could wiggle or bounce to draw attention. It would be fun to have a confetti animation on the initial entrance.

![random event](https://user-images.githubusercontent.com/21324742/34658230-08311a2c-f3f3-11e7-8f4b-fa73eaceb326.png)

Here's the Figma link if you want to log in and check it out: https://www.figma.com/file/LQPgYVMqpla98ZGwHye749/Random-Events
