### ISSUE TITLE
Breakout: Levels

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#94]
Levels currently do not advance when all destructible blocks are gone, instead the level advance seems to be triggered by the ball falling below the paddle.

If the ball falls below the paddle, a failure state should be triggered, and it should show the player's final score and give them the option to restart from the beginning.

**Comment by ZigaByte** [comment]
Correct. The level is also changed if you destroy all of the blocks, but the indestructible are sadly indestructible. I will fix it

**Comment by ZigaByte** [comment]
Fixed the level advancement

**Comment by Jeremy-Barnes** [comment]
In the current build, levels still advance on loss. Not sure if thats what you meant. Maybe the merge broke it?

**Comment by ZigaByte** [comment]
I have not implemented the Game Over screen yet.

**Comment by Jeremy-Barnes** [comment]
Oh, did you fix it so that the level advances when all the breakable bricks are gone?

**Comment by ZigaByte** [comment]
Yes
